import { SETTING_FORM_CONFIG } from '@configs/setting.configs';


export const formFieldsData = [
  {
    id: 1,
    label: 'Dictionary Time',
    type: 'number',
    inputMode: 'numeric',
    formControlName: 'dictionaryTime',
    config: SETTING_FORM_CONFIG.dictionaryTime,
    placeholder: '0',
    prefix: 'schedule',
    suffix: 'min',
  },
  {
    id: 2,
    label: 'Dictionary passing score',
    type: 'number',
    inputMode: 'numeric',
    formControlName: 'dictionaryPassingScore',
    config: SETTING_FORM_CONFIG.dictionaryPassingScore,
    placeholder: '0',
    prefix: 'sports_score',
    suffix: '%',
  },
  {
    id: 3,
    label: 'Testing Time',
    type: 'number',
    inputMode: 'numeric',
    formControlName: 'testingTime',
    config: SETTING_FORM_CONFIG.testingTime,
    placeholder: '0',
    prefix: 'schedule',
    suffix: 'min',
  },
  {
    id: 4,
    label: 'Testing passing score',
    type: 'number',
    inputMode: 'numeric',
    formControlName: 'testingPassingScore',
    config: SETTING_FORM_CONFIG.testingPassingScore,
    placeholder: '0',
    prefix: 'sports_score',
    suffix: '%',
  },
  {
    id: 5,
    label: 'Writing Symbol Length',
    type: 'number',
    inputMode: 'numeric',
    formControlName: 'writingSymbolLength',
    config: SETTING_FORM_CONFIG.writingSymbolLength,
    placeholder: '0',
    prefix: 'emergency',
    suffix: '',
  },
  {
    id: 6,
    label: 'Block quize time',
    type: 'number',
    inputMode: 'numeric',
    formControlName: 'blockQuizeTime',
    config: SETTING_FORM_CONFIG.blockQuizeTime,
    placeholder: '0',
    prefix: 'block',
    suffix: 'hour',
  },
  {
    id: 7,
    label: 'Listening Audio Replay',
    type: 'number',
    inputMode: 'numeric',
    formControlName: 'listeningAudioReplay',
    config: SETTING_FORM_CONFIG.listeningAutioReplay,
    placeholder: '0',
    prefix: 'replay_5',
    suffix: 'times',
  },
];
