import { UsersDocument } from '@admin/admin.interface';
import { TableData } from '@components/table/table.interface';
import { CreateUserComponent } from '@admin/components/create-user/create-user.component';

export const UsersDocumentsData: UsersDocument[] = [
  {
    _id: 1,
    avatar: 'assets/signin.png',
    fullName: 'Ikrom Qodirov',
    email: 'jamoliddinqodirov18@gmail.com',
    password: '234234234',
    role: 'STUDENT',
    level: 'beginner',
    description: 'My description about student',
  },
  {
    _id: 2,
    avatar: 'assets/history.png',
    fullName: 'Vali Azimov',
    email: 'jamoliddinqodirov18@gmail.com',
    password: '234234234',
    role: 'STUDENT',
    level: 'beginner',
    description: 'My description about student',
  },
  {
    _id: 3,
    avatar: 'assets/dictionary.png',
    fullName: 'maysara iqrorova',
    email: 'jamoliddinqodirov18@gmail.com',
    password: '234234234',
    role: 'STUDENT',
    level: 'beginner',
    description: 'My description about student',
  },
  {
    _id: 4,
    avatar: 'assets/dictionary.png',
    fullName: 'jonibek ghafuro',
    email: 'jgafurov@gmail.com',
    password: '234234234',
    role: 'STUDENT',
    level: 'beginner',
    description: 'My description about student',
  },
  {
    _id: 5,
    avatar: 'assets/testing.png',
    fullName: 'Jamoliddin Qodirov',
    email: 'jamoliddinqodirov18@gmail.com',
    password: '234234234',
    role: 'STUDENT',
    level: 'beginner',
    description: 'My description about student',
  },
  {
    _id: 6,
    avatar: 'assets/testing.png',
    fullName: 'Jamoliddin Qodirov',
    email: 'jamoliddinqodirov18@gmail.com',
    password: '234234234',
    role: 'ADMIN',
    level: 'elementary',
    description: 'My description about student',
  },
  {
    _id: 7,
    avatar: 'assets/dictionary.png',
    fullName: 'Jamoliddin Qodirov',
    email: 'jamoliddinqodirov18@gmail.com',
    password: '234234234',
    role: 'STUDENT',
    level: 'beginner',
    description: 'My description about student',
  },
  {
    _id: 8,
    avatar: 'assets/dictionary.png',
    fullName: 'Jamoliddin Qodirov',
    email: 'jamoliddinqodirov18@gmail.com',
    password: '234234234',
    role: 'STUDENT',
    level: 'beginner',
    description: 'My description about student',
  },
  {
    _id: 9,
    avatar: 'assets/dictionary.png',
    fullName: 'Jamoliddin Qodirov',
    email: 'jamoliddinqodirov18@gmail.com',
    password: '234234234',
    role: 'STUDENT',
    level: 'beginner',
    description: 'My description about student',
  },
  {
    _id: 10,
    avatar: 'assets/signin.png',
    fullName: 'Komila Jabborova',
    email: 'kjaborova@gmail.com',
    password: '234234234',
    role: 'STUDENT',
    level: 'beginner',
    description: 'My description about student',
  },
  {
    _id: 11,
    avatar: 'assets/student.jpg',
    fullName: 'Asal Urunova',
    email: 'jamoliddinqodirov18@gmail.com',
    password: '234234234',
    role: 'STUDENT',
    level: 'beginner',
    description: 'My description about student',
  },
  {
    _id: 12,
    avatar: 'assets/dictionary.png',
    fullName: 'Laylo Sharipova',
    email: 'jamoliddinqodirov18@gmail.com',
    password: '234234234',
    role: 'STUDENT',
    level: 'beginner',
    description: 'My description about student',
  },
  {
    _id: 13,
    avatar: 'assets/dictionary.png',
    fullName: 'Mumin Azizoda',
    email: 'jamoliddinqodirov18@gmail.com',
    password: '234234234',
    role: 'STUDENT',
    level: 'beginner',
    description: 'My description about student',
  },
  {
    _id: 14,
    avatar: 'assets/testing.png',
    fullName: 'Zebo Nematova',
    email: 'znematova@gmail.com',
    password: '234234234',
    role: 'STUDENT',
    level: 'beginner',
    description: 'My description about student',
  },
  {
    _id: 15,
    avatar: 'assets/admin.png',
    fullName: 'sayfura temurbekova',
    email: 'stemurbek@gmail.com',
    password: '234234234',
    role: 'STUDENT',
    level: 'beginner',
    description: 'My description about student',
  },
  {
    _id: 16,
    avatar: 'assets/dictionary.png',
    fullName: 'Mijgona Bobeva',
    email: 'jamoliddinqodirov18@gmail.com',
    password: '234234234',
    role: 'STUDENT',
    level: 'beginner',
    description: 'My description about student',
  },
  {
    _id: 17,
    avatar: 'assets/dictionary.png',
    fullName: 'Maysar Qodirova',
    email: 'jamoliddinqodirov18@gmail.com',
    password: '234234234',
    role: 'STUDENT',
    level: 'beginner',
    description: 'My description about student',
  },
  {
    _id: 18,
    avatar: 'assets/signin.png',
    fullName: 'Jonona rametova',
    email: 'jamoliddinqodirov18@gmail.com',
    password: '234234234',
    role: 'STUDENT',
    level: 'beginner',
    description: 'My description about student',
  },
  {
    _id: 19,
    avatar: 'assets/dictionary.png',
    fullName: 'Jabbor davlatov',
    email: 'jamoliddinqodirov18@gmail.com',
    password: '234234234',
    role: 'STUDENT',
    level: 'beginner',
    description: 'My description about student',
  },
  {
    _id: 20,
    avatar: 'assets/dictionary.png',
    fullName: 'Daler Halimov',
    email: 'jamoliddinqodirov18@gmail.com',
    password: '234234234',
    role: 'STUDENT',
    level: 'beginner',
    description: 'My description about student',
  },
];

export const usersTableData: TableData<CreateUserComponent> = {

  id: { header: 'update', property: '_id', tooltip: 'Update current user' },
  columns: [
    { header: 'Full Name', property: 'fullName', tooltip: 'Full name of current user' },
    { header: 'Role', property: 'role', tooltip: 'Current user role (Admin | Student)' },
  ],
  avatar: { header: 'avatar', property: 'avatar', tooltip: 'Avatar image of user' },
  dialogComponent: CreateUserComponent
}